"""add product_targets junction table

Revision ID: 37b7763072a4
Revises: 9d4b89003e72
Create Date: 2026-07-27 02:42:08.404001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37b7763072a4'
down_revision: Union[str, Sequence[str], None] = '9d4b89003e72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['scrape_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'target_id', name='uq_product_targets_product_target')
    )
    op.create_index(op.f('ix_product_targets_product_id'), 'product_targets', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_targets_target_id'), 'product_targets', ['target_id'], unique=False)
    op.alter_column('stores', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'base_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('stores', 'search_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('stores', 'product_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'product_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('stores', 'search_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('stores', 'base_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stores', 'domain',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_product_targets_target_id'), table_name='product_targets')
    op.drop_index(op.f('ix_product_targets_product_id'), table_name='product_targets')
    op.drop_table('product_targets')
    # ### end Alembic commands ###
