"""create_scrape_target

Revision ID: 62a9388defe0
Revises: 5a4311731a75
Create Date: 2026-07-23 17:05:41.852373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62a9388defe0'
down_revision: Union[str, Sequence[str], None] = '5a4311731a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_target',
    sa.Column('tid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sid', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.SmallInteger(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('schedule_type', sa.SmallInteger(), nullable=False),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('next_scrape_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sid'], ['store.sid'],ondelete="CASCADE", ),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_index(op.f('ix_scrape_target_next_scrape_at'), 'scrape_target', ['next_scrape_at'], unique=False)
    op.create_index(op.f('ix_scrape_target_sid'), 'scrape_target', ['sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_target_sid'), table_name='scrape_target')
    op.drop_index(op.f('ix_scrape_target_next_scrape_at'), table_name='scrape_target')
    op.drop_table('scrape_target')
    # ### end Alembic commands ###
