"""add category specs tables

Revision ID: 6e382c2f1976
Revises: 37b7763072a4
Create Date: 2026-07-27 03:07:52.672210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e382c2f1976'
down_revision: Union[str, Sequence[str], None] = '37b7763072a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinet_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('max_gpu_length_mm', sa.Integer(), nullable=True),
    sa.Column('max_cooler_height_mm', sa.Integer(), nullable=True),
    sa.Column('max_psu_length_mm', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinet_specs_product_id'), 'cabinet_specs', ['product_id'], unique=True)
    op.create_table('cooler_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cooler_type', sa.String(length=50), nullable=True),
    sa.Column('radiator_size_mm', sa.Integer(), nullable=True),
    sa.Column('fan_size_mm', sa.Integer(), nullable=True),
    sa.Column('supported_sockets', sa.String(length=255), nullable=True),
    sa.Column('tdp_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooler_specs_product_id'), 'cooler_specs', ['product_id'], unique=True)
    op.create_table('cpu_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('socket', sa.String(length=50), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('base_clock', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('boost_clock', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tdp', sa.Integer(), nullable=True),
    sa.Column('integrated_graphics', sa.Boolean(), nullable=True),
    sa.Column('architecture', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpu_specs_product_id'), 'cpu_specs', ['product_id'], unique=True)
    op.create_index(op.f('ix_cpu_specs_socket'), 'cpu_specs', ['socket'], unique=False)
    op.create_table('gpu_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('chipset', sa.String(length=100), nullable=True),
    sa.Column('memory_size_gb', sa.Integer(), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=True),
    sa.Column('tdp', sa.Integer(), nullable=True),
    sa.Column('recommended_psu', sa.Integer(), nullable=True),
    sa.Column('length_mm', sa.Integer(), nullable=True),
    sa.Column('slot_width', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_specs_chipset'), 'gpu_specs', ['chipset'], unique=False)
    op.create_index(op.f('ix_gpu_specs_product_id'), 'gpu_specs', ['product_id'], unique=True)
    op.create_table('monitor_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('screen_size_inch', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('resolution', sa.String(length=50), nullable=True),
    sa.Column('refresh_rate_hz', sa.Integer(), nullable=True),
    sa.Column('panel_type', sa.String(length=20), nullable=True),
    sa.Column('response_time_ms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_specs_product_id'), 'monitor_specs', ['product_id'], unique=True)
    op.create_table('motherboard_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('socket', sa.String(length=50), nullable=True),
    sa.Column('chipset', sa.String(length=50), nullable=True),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=True),
    sa.Column('memory_slots', sa.Integer(), nullable=True),
    sa.Column('max_memory_gb', sa.Integer(), nullable=True),
    sa.Column('m2_slots', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_motherboard_specs_product_id'), 'motherboard_specs', ['product_id'], unique=True)
    op.create_index(op.f('ix_motherboard_specs_socket'), 'motherboard_specs', ['socket'], unique=False)
    op.create_table('psu_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('wattage', sa.Integer(), nullable=True),
    sa.Column('efficiency_rating', sa.String(length=50), nullable=True),
    sa.Column('modularity', sa.String(length=50), nullable=True),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psu_specs_product_id'), 'psu_specs', ['product_id'], unique=True)
    op.create_index(op.f('ix_psu_specs_wattage'), 'psu_specs', ['wattage'], unique=False)
    op.create_table('ram_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=True),
    sa.Column('speed_mhz', sa.Integer(), nullable=True),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('modules', sa.Integer(), nullable=True),
    sa.Column('latency_cl', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ram_specs_memory_type'), 'ram_specs', ['memory_type'], unique=False)
    op.create_index(op.f('ix_ram_specs_product_id'), 'ram_specs', ['product_id'], unique=True)
    op.create_table('ssd_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('capacity_gb', sa.Integer(), nullable=True),
    sa.Column('form_factor', sa.String(length=50), nullable=True),
    sa.Column('interface', sa.String(length=50), nullable=True),
    sa.Column('read_speed_mbps', sa.Integer(), nullable=True),
    sa.Column('write_speed_mbps', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ssd_specs_product_id'), 'ssd_specs', ['product_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.drop_index(op.f('ix_ssd_specs_product_id'), table_name='ssd_specs')
    op.drop_table('ssd_specs')
    op.drop_index(op.f('ix_ram_specs_product_id'), table_name='ram_specs')
    op.drop_index(op.f('ix_ram_specs_memory_type'), table_name='ram_specs')
    op.drop_table('ram_specs')
    op.drop_index(op.f('ix_psu_specs_wattage'), table_name='psu_specs')
    op.drop_index(op.f('ix_psu_specs_product_id'), table_name='psu_specs')
    op.drop_table('psu_specs')
    op.drop_index(op.f('ix_motherboard_specs_socket'), table_name='motherboard_specs')
    op.drop_index(op.f('ix_motherboard_specs_product_id'), table_name='motherboard_specs')
    op.drop_table('motherboard_specs')
    op.drop_index(op.f('ix_monitor_specs_product_id'), table_name='monitor_specs')
    op.drop_table('monitor_specs')
    op.drop_index(op.f('ix_gpu_specs_product_id'), table_name='gpu_specs')
    op.drop_index(op.f('ix_gpu_specs_chipset'), table_name='gpu_specs')
    op.drop_table('gpu_specs')
    op.drop_index(op.f('ix_cpu_specs_socket'), table_name='cpu_specs')
    op.drop_index(op.f('ix_cpu_specs_product_id'), table_name='cpu_specs')
    op.drop_table('cpu_specs')
    op.drop_index(op.f('ix_cooler_specs_product_id'), table_name='cooler_specs')
    op.drop_table('cooler_specs')
    op.drop_index(op.f('ix_cabinet_specs_product_id'), table_name='cabinet_specs')
    op.drop_table('cabinet_specs')
    # ### end Alembic commands ###
