"""add search_url_template

Revision ID: f5c498b97315
Revises: 6b3dbe4850ce
Create Date: 2026-07-25 01:41:32.792032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c498b97315'
down_revision: Union[str, Sequence[str], None] = '6b3dbe4850ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Step 1: Add the column as nullable
    op.add_column(
        "stores",
        sa.Column(
            "search_url_template",
            sa.String(),
            nullable=True,
        ),
    )

    # Step 2: Populate existing rows
    op.execute("""
        UPDATE stores
        SET search_url_template =
            'https://mdcomputers.in/catalogsearch/result/?q={query}'
        WHERE name = 'mdcomputers'
    """)

    # Step 3: Make it NOT NULL
    op.alter_column(
        "stores",
        "search_url_template",
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'search_url_template')
    # ### end Alembic commands ###
